// property
const PROPERTY_ADD_THREAD = ['title', 'body', 'owner', 'date']
const PROPERTY_ADDED_THREAD = ['id', 'title', 'owner']
const PROPERTY_ADDED_COMMENT = ['id', 'content', 'owner']
const PROPERTY_AUTHENTICATION = ['refreshToken']
const PROPERTY_NEW_AUTHENTICATION = ['accessToken', 'refreshToken']
const PROPERTY_REGISTERED_USER = ['id', 'username', 'fullname']
const PROPERTY_REGISTER_USER = ['username', 'password', 'fullname']
const PROPERTY_USER_LOGIN = ['username', 'password']
const PROPERTY_DETAIL_THREAD = ['id', 'title', 'body', 'date', 'username', 'comments']

// value property
const ACCESS_TOKEN = 'access_token'
const ACCESS_TOKEN_WITHOUT_UNDERSCORE = 'accessToken'
const HEADER_AUTHORIZATION = 'Bearer accessToken'
const FAKE_BAD_VALUE_THREAD = 'zxc'
const FAKE_BAD_VALUE_USER = 'zxc'
const FAKE_BAD_INPUT_VALUE_THREAD = 24212
const FAKE_VALUE_GREATER_THAN_LIMIT = 'thread-123thread-123thread-123thread-123thread-123thread-123thread-123'
const FAKE_ID_THREAD = 'thread-123'
const FAKE_TITLE_THREAD = 'this title thread'
const FAKE_BODY_THREAD = 'this body fake'
const FAKE_OWNER_THREAD = 'user-123'
const FAKE_DATE_THREAD = '2023-02-15'
const FAKE_ID_WITH_WHITE_SPACE = 'thread - 123'
const FAKE_OWNER_WITH_WHITE_SPACE = 'user - 123'
const FAKE_USER_PASSWORD = 'dummy_password'
const FAKE_PLAIN_PASSWORD = 'plain'
const FAKE_PLAIN_PASSWORDS = 'plain_password'
const FAKE_ENCRYPTED_PASSWORD = 'encrypted'
const FAKE_ENCRYPTED_PASSWORDS = 'encrypted_password'
const FAKE_USERNAME = 'dicoding'
const FAKE_USERNAME_WITH_WHITE_SPACE = 'dico ding'
const FAKE_PASSWORD = 'secret'
const FAKE_FULLNAME = 'Dicoding Indonesia'
const FAKE_ENCRYPTED = 'encrypted password'
const FAKE_INVALID_REFRESH_TOKEN = 'invalid_refresh_token'
const FAKE_PASSWORD_SECRET = 'super_secret'
const FAKE_COMMENT_ID = 'comment-123'
const FAKE_COMMENT_CONTENT = 'this comment'
const FAKE_ARRAY_COMMENT = [
  {
    id: FAKE_COMMENT_ID,
    username: `${FAKE_USERNAME} indonesia`,
    date: FAKE_DATE_THREAD,
    content: FAKE_COMMENT_CONTENT
  }
]
const MOCK_TOKEN = 'mock_token'
const REFRESH_TOKEN = 'refreshToken'
const REFRESH_TOKEN_UNDERSCORE = ' refresh_token'
const SOME_REFRESH_TOKEN = 'some_refresh_token'
const SOME_NEW_ACCESS_TOKEN = 'some_new_access_token'
const SOME_ERROR_MESSAGE = 'some_error_message'
const STATUS_SUCCESS = 'success'
const STATUS_FAIL = 'fail'
const STATUS_ERROR = 'error'
const TOKEN = 'token'

// throw error
const ERR_ADD_THREAD_NEED_PROPERTY = 'ADD_THREAD.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_ADD_THREAD_DATA_TYPE_SPECIFICATION = 'ADD_THREAD.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_ADD_THREAD_ID_LIMIT_CHARACTER = 'ADD_THREAD.ID_LIMIT_CHARACTER'
const ERR_ADD_THREAD_TITLE_LIMIT_CHARACTER = 'ADD_THREAD.TITLE_LIMIT_CHARACTER'
const ERR_ADD_THREAD_OWNER_LIMIT_CHARACTER = 'ADD_THREAD.OWNER_LIMIT_CHARACTER'
const ERR_ADD_THREAD_ID_WITH_WHITE_SPACE = 'ADD_THREAD.ID_CONTAIN_WHITE_SPACE_CHARACTER'
const ERR_ADD_THREAD_OWNER_WITH_WHITE_SPACE = 'ADD_THREAD.OWNER_CONTAIN_WHITE_SPACE_CHARACTER'
const ERR_ADDED_THREAD_NOT_CONTAIN_NEEDED_PROPERTY = 'ADDED_THREAD.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_ADDED_THREAD_USER_NOT_MEET_DATA_TYPE_SPECIFICATION = 'ADDED_THREAD.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_AUTHENTICATION_TOKEN_MANAGER = 'AUTHENTICATION_TOKEN_MANAGER.METHOD_NOT_IMPLEMENTED'
const ERR_PASSWORD_HASH = 'PASSWORD_HASH.METHOD_NOT_IMPLEMENTED'
const ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN = 'DELETE_AUTHENTICATION_USE_CASE.NOT_CONTAIN_REFRESH_TOKEN'
const ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_MEET_DATA_TYPE_SPECIFICATION = 'DELETE_AUTHENTICATION_USE_CASE.PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_REFRESH_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN = 'REFRESH_AUTHENTICATION_USE_CASE.NOT_CONTAIN_REFRESH_TOKEN'
const ERR_REFRESH_USE_CASE_PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION = 'REFRESH_AUTHENTICATION_USE_CASE.PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_AUTHENTICATION_REPOSITORY_METHOD_NOT_IMPLEMENTED = 'AUTHENTICATION_REPOSITORY.METHOD_NOT_IMPLEMENTED'
const ERR_NEW_AUTH_NOT_CONTAIN_NEEDED_PROPERTY = 'NEW_AUTH.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_NEW_AUTH_NOT_MEET_DATA_TYPE_SPECIFICATION = 'NEW_AUTH.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_USER_REPOSITORY_METHOD_NOT_IMPLEMENTED = 'USER_REPOSITORY.METHOD_NOT_IMPLEMENTED'
const ERR_REGISTERED_NOT_CONTAIN_NEEDED_PROPERTY = 'REGISTERED_USER.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_REGISTERED_USER_NOT_MEET_DATA_TYPE_SPECIFICATION = 'REGISTERED_USER.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_REGISTER_USER_NOT_CONTAIN_NEEDED_PROPERTY = 'REGISTER_USER.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_REGISTER_USER_NOT_MEET_DATA_TYPE_SPECIFICATION = 'REGISTER_USER.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_REGISTER_USER_USERNAME_LIMIT_CHAR = 'REGISTER_USER.USERNAME_LIMIT_CHAR'
const ERR_REGISTER_USER_USERNAME_RESTRICTED_CHARACTER = 'REGISTER_USER.USERNAME_CONTAIN_RESTRICTED_CHARACTER'
const ERR_LOGIN_NOT_CONTAIN_NEEDED_PROPERTY = 'USER_LOGIN.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_LOGIN_NOT_MEET_DATA_TYPE_SPECIFICATION = 'USER_LOGIN.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_THREAD_REPOSITORY_METHOD_NOT_IMPLEMENTED = 'THREAD_REPOSITORY.METHOD_NOT_IMPLEMENTED'
const ERR_ADD_COMMENT_NEED_PROPERTY = 'ADD_COMMENT.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_ADD_COMMENT_DATA_TYPE_SPECIFICATION = 'ADD_COMMENT.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_ADD_COMMENT_THREAD_ID_LIMIT_CHARACTER = 'ADD_COMMENT.THREAD_ID_LIMIT_CHARACTER'
const ERR_ADD_COMMENT_OWNER_LIMIT_CHARACTER = 'ADD_COMMENT.OWNER_LIMIT_CHARACTER'
const ERR_ADD_COMMENT_THREAD_ID_WITH_WHITE_SPACE = 'ADD_COMMENT.THREAD_ID_CONTAIN_WHITE_SPACE_CHARACTER'
const ERR_ADD_COMMENT_OWNER_WITH_WHITE_SPACE = 'ADD_COMMENT.OWNER_CONTAIN_WHITE_SPACE_CHARACTER'
const ERR_ADDED_COMMENT_NOT_CONTAIN_NEEDED_PROPERTY = 'ADDED_COMMENT.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_ADDED_COMMENT_USER_NOT_MEET_DATA_TYPE_SPECIFICATION = 'ADDED_COMMENT.NOT_MEET_DATA_TYPE_SPECIFICATION'
const ERR_COMMENT_REPOSITORY_METHOD_NOT_IMPLEMENTED = 'COMMENT_REPOSITORY.METHOD_NOT_IMPLEMENTED'
const ERR_DETAIL_THREAD_NOT_CONTAIN_NEEDED_PROPERTY = 'DETAIL_THREAD.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_DETAIL_THREAD_NOT_MEET_DATA_SPECIFICATION = 'DETAIL_THREAD.NOT_MEET_DATA_SPECIFICATION'
const ERR_DETAIL_COMMENT_NOT_CONTAIN_NEEDED_PROPERTY = 'DETAIL_COMMENT.NOT_CONTAIN_NEEDED_PROPERTY'
const ERR_DETAIL_COMMENT_NOT_MEET_DATA_SPECIFICATION = 'DETAIL_COMMENT.NOT_MEET_DATA_SPECIFICATION'

// error name
const ERR_AUTHENTICATION_ERROR_SMALL = 'authentication error!'
const ERR_AUTHENTICATION_ERROR = 'AuthenticationError'
const ERR_AUTHORIZATION_ERROR_SMALL = 'authorization error!'
const ERR_AUTHORIZATION_ERROR = 'AuthorizationError'
const ERR_ABSTRACT_CLASS = 'cannot instantiate abstract class'
const ERR_CLIENT_ERROR = 'ClientError'
const ERR_OCCRUS = 'an error occurs'
const ERR_INVARIANT_ERROR = 'InvariantError'
const ERR_NOT_FOUND_SMALL = 'not found!'
const ERR_NOT_FOUND = 'NotFoundError'

// error message
const ERR_MSG_USERNAME_NOT_FINDED = 'username not finded'
const ERR_MSG_WRONG_CREDENTIAL = 'your credential is invalid'
const ERR_MSG_MUST_SEND_USERNAME_AND_PASSWORD = 'you must send username and password'
const ERR_MSG_DATA_TYPE_USERNAME_PASSWORD_MUST_STRING = 'username and password must string'
const ERR_MSG_MUST_SEND_REFRESH_TOKEN = 'you must send refresh token'
const ERR_MSG_REFRESH_TOKEN_MUST_STRING = 'refresh token must string'
const ERR_MSG_REFRESH_TOKEN_NOT_VALID = 'refresh token tidak valid'
const ERR_MSG_REFRESH_TOKEN_NOT_FOUNDED_IN_DATABASE = 'refresh token tidak ditemukan di database'
const ERR_MSG_ACCESS_TOKEN_NOT_VALID = 'access token tidak valid'
const ERR_MSG_INTERNAL_SERVER_ERROR = 'there was a failure on our server'
const ERR_MSG_CANNOT_CREATE_USER = 'cannot create a new user because the required property does not exist'
const ERR_MSG_CANNOT_CREATE_USER_BECAUSE_DATA_TYPE = 'unable to create a new user because the data type does not match'
const ERR_MSG_CANNOT_CREATE_USER_BECAUSE_USERNAME_LIMIT = 'cannot create a new user because the username character exceeds the limit'
const ERR_MSG_CANNOT_CREATE_USER_BECAUSE_RESTRICTED_CHARACTER = 'tidak dapat membuat user baru karena username mengandung karakter terlarang'
const ERR_MSG_USERNAME_NOT_AVAILABLE = 'username tidak tersedia'
const ERR_MGS_USER_NOT_FOUND = 'user not found'
const ERR_MSG_CANNOT_CREATE_THREAD = 'cannot create a new thread because the required property does not exist'
const ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_DATA_TYPE = 'unable to create a new thread because the data type does not match'
const ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_TITLE_LIMIT = 'cannot create a new thread because the title character exceeds the limit'
const ERR_MSG_MISSING_TOKEN_AUTHENTICATION = 'Missing authentication'
const ERR_MSG_THREAD_NOT_FOUND = 'thread not found'
const ERR_MSG_CANNOT_CREATE_COMMENT = 'cannot create a new comment because the required property does not exist'
const ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_DATA_TYPE = 'unable to create a new comment because the data type does not match'
const ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_THREAD_ID_LIMIT = 'cannot create a new comment because the thread id character exceeds the limit'
const ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_OWNER_LIMIT = 'cannot create a new comment because an owner character exceeds the limit'
const ERR_MSG_CANNOT_DELETE_COMMENT = 'tidak bisa menghapus comment karena comment tidak ada'
const ERR_MSG_CANNOT_ACCESS_COMMENT = 'proses gagal karena Anda tidak mempunyai akses ke aksi ini'
const ERR_MSG_COMMENT_NOT_FOUND = 'comment yang Anda cari tidak ada'
const ERR_MSG_COMMENT_NOT_FOUND_IN_THREAD = 'comment yang Anda cari tidak ada'

module.exports = {
  PROPERTY_ADD_THREAD,
  PROPERTY_ADDED_THREAD,
  PROPERTY_AUTHENTICATION,
  PROPERTY_NEW_AUTHENTICATION,
  PROPERTY_REGISTERED_USER,
  PROPERTY_REGISTER_USER,
  PROPERTY_USER_LOGIN,
  PROPERTY_ADDED_COMMENT,
  PROPERTY_DETAIL_THREAD,
  ACCESS_TOKEN,
  ACCESS_TOKEN_WITHOUT_UNDERSCORE,
  HEADER_AUTHORIZATION,
  FAKE_BAD_VALUE_THREAD,
  FAKE_BAD_VALUE_USER,
  FAKE_BAD_INPUT_VALUE_THREAD,
  FAKE_VALUE_GREATER_THAN_LIMIT,
  FAKE_ID_THREAD,
  FAKE_TITLE_THREAD,
  FAKE_BODY_THREAD,
  FAKE_OWNER_THREAD,
  FAKE_DATE_THREAD,
  FAKE_ID_WITH_WHITE_SPACE,
  FAKE_OWNER_WITH_WHITE_SPACE,
  FAKE_USER_PASSWORD,
  FAKE_PLAIN_PASSWORD,
  FAKE_PLAIN_PASSWORDS,
  FAKE_ENCRYPTED_PASSWORD,
  FAKE_ENCRYPTED_PASSWORDS,
  FAKE_USERNAME,
  FAKE_USERNAME_WITH_WHITE_SPACE,
  FAKE_PASSWORD,
  FAKE_FULLNAME,
  FAKE_ENCRYPTED,
  FAKE_INVALID_REFRESH_TOKEN,
  FAKE_PASSWORD_SECRET,
  FAKE_COMMENT_ID,
  FAKE_COMMENT_CONTENT,
  FAKE_ARRAY_COMMENT,
  MOCK_TOKEN,
  REFRESH_TOKEN,
  REFRESH_TOKEN_UNDERSCORE,
  STATUS_SUCCESS,
  STATUS_FAIL,
  STATUS_ERROR,
  SOME_REFRESH_TOKEN,
  SOME_NEW_ACCESS_TOKEN,
  SOME_ERROR_MESSAGE,
  TOKEN,
  ERR_ADD_THREAD_NEED_PROPERTY,
  ERR_ADD_THREAD_DATA_TYPE_SPECIFICATION,
  ERR_ADD_THREAD_ID_LIMIT_CHARACTER,
  ERR_ADD_THREAD_TITLE_LIMIT_CHARACTER,
  ERR_ADD_THREAD_OWNER_LIMIT_CHARACTER,
  ERR_ADD_THREAD_ID_WITH_WHITE_SPACE,
  ERR_ADD_THREAD_OWNER_WITH_WHITE_SPACE,
  ERR_ADDED_THREAD_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_ADDED_THREAD_USER_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_AUTHENTICATION_TOKEN_MANAGER,
  ERR_PASSWORD_HASH,
  ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN,
  ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_REFRESH_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN,
  ERR_REFRESH_USE_CASE_PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_AUTHENTICATION_REPOSITORY_METHOD_NOT_IMPLEMENTED,
  ERR_NEW_AUTH_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_NEW_AUTH_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_USER_REPOSITORY_METHOD_NOT_IMPLEMENTED,
  ERR_REGISTERED_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_REGISTERED_USER_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_REGISTER_USER_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_REGISTER_USER_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_REGISTER_USER_USERNAME_LIMIT_CHAR,
  ERR_REGISTER_USER_USERNAME_RESTRICTED_CHARACTER,
  ERR_LOGIN_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_LOGIN_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_THREAD_REPOSITORY_METHOD_NOT_IMPLEMENTED,
  ERR_ADD_COMMENT_NEED_PROPERTY,
  ERR_ADD_COMMENT_DATA_TYPE_SPECIFICATION,
  ERR_ADD_COMMENT_THREAD_ID_LIMIT_CHARACTER,
  ERR_ADD_COMMENT_OWNER_LIMIT_CHARACTER,
  ERR_ADD_COMMENT_THREAD_ID_WITH_WHITE_SPACE,
  ERR_ADD_COMMENT_OWNER_WITH_WHITE_SPACE,
  ERR_ADDED_COMMENT_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_ADDED_COMMENT_USER_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_DETAIL_THREAD_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_DETAIL_THREAD_NOT_MEET_DATA_SPECIFICATION,
  ERR_DETAIL_COMMENT_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_DETAIL_COMMENT_NOT_MEET_DATA_SPECIFICATION,
  ERR_COMMENT_REPOSITORY_METHOD_NOT_IMPLEMENTED,
  ERR_AUTHENTICATION_ERROR_SMALL,
  ERR_AUTHENTICATION_ERROR,
  ERR_AUTHORIZATION_ERROR_SMALL,
  ERR_AUTHORIZATION_ERROR,
  ERR_CLIENT_ERROR,
  ERR_ABSTRACT_CLASS,
  ERR_OCCRUS,
  ERR_INVARIANT_ERROR,
  ERR_NOT_FOUND_SMALL,
  ERR_NOT_FOUND,
  ERR_MSG_USERNAME_NOT_FINDED,
  ERR_MSG_WRONG_CREDENTIAL,
  ERR_MSG_MUST_SEND_USERNAME_AND_PASSWORD,
  ERR_MSG_DATA_TYPE_USERNAME_PASSWORD_MUST_STRING,
  ERR_MSG_MUST_SEND_REFRESH_TOKEN,
  ERR_MSG_REFRESH_TOKEN_MUST_STRING,
  ERR_MSG_REFRESH_TOKEN_NOT_VALID,
  ERR_MSG_REFRESH_TOKEN_NOT_FOUNDED_IN_DATABASE,
  ERR_MSG_ACCESS_TOKEN_NOT_VALID,
  ERR_MSG_INTERNAL_SERVER_ERROR,
  ERR_MSG_CANNOT_CREATE_USER,
  ERR_MSG_CANNOT_CREATE_USER_BECAUSE_DATA_TYPE,
  ERR_MSG_CANNOT_CREATE_USER_BECAUSE_USERNAME_LIMIT,
  ERR_MSG_CANNOT_CREATE_USER_BECAUSE_RESTRICTED_CHARACTER,
  ERR_MSG_USERNAME_NOT_AVAILABLE,
  ERR_MGS_USER_NOT_FOUND,
  ERR_MSG_CANNOT_CREATE_THREAD,
  ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_DATA_TYPE,
  ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_TITLE_LIMIT,
  ERR_MSG_MISSING_TOKEN_AUTHENTICATION,
  ERR_MSG_THREAD_NOT_FOUND,
  ERR_MSG_CANNOT_CREATE_COMMENT,
  ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_DATA_TYPE,
  ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_THREAD_ID_LIMIT,
  ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_OWNER_LIMIT,
  ERR_MSG_CANNOT_DELETE_COMMENT,
  ERR_MSG_CANNOT_ACCESS_COMMENT,
  ERR_MSG_COMMENT_NOT_FOUND,
  ERR_MSG_COMMENT_NOT_FOUND_IN_THREAD
}
