const InvariantError = require('./InvariantError')

const {
  ERR_MSG_MUST_SEND_USERNAME_AND_PASSWORD,
  ERR_MSG_DATA_TYPE_USERNAME_PASSWORD_MUST_STRING,
  ERR_MSG_MUST_SEND_REFRESH_TOKEN,
  ERR_MSG_REFRESH_TOKEN_MUST_STRING,
  ERR_MSG_CANNOT_CREATE_USER,
  ERR_MSG_CANNOT_CREATE_USER_BECAUSE_DATA_TYPE,
  ERR_MSG_CANNOT_CREATE_USER_BECAUSE_USERNAME_LIMIT,
  ERR_MSG_CANNOT_CREATE_USER_BECAUSE_RESTRICTED_CHARACTER,
  ERR_REGISTER_USER_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_REGISTER_USER_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_REGISTER_USER_USERNAME_LIMIT_CHAR,
  ERR_REGISTER_USER_USERNAME_RESTRICTED_CHARACTER,
  ERR_LOGIN_NOT_CONTAIN_NEEDED_PROPERTY,
  ERR_LOGIN_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_REFRESH_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN,
  ERR_REFRESH_USE_CASE_PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN,
  ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_MEET_DATA_TYPE_SPECIFICATION,
  ERR_ADD_THREAD_DATA_TYPE_SPECIFICATION,
  ERR_MSG_CANNOT_CREATE_THREAD,
  ERR_ADD_THREAD_NEED_PROPERTY,
  ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_DATA_TYPE,
  ERR_ADD_THREAD_TITLE_LIMIT_CHARACTER,
  ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_TITLE_LIMIT,
  ERR_ADD_COMMENT_NEED_PROPERTY,
  ERR_ADD_COMMENT_DATA_TYPE_SPECIFICATION,
  ERR_ADD_COMMENT_THREAD_ID_LIMIT_CHARACTER,
  ERR_ADD_COMMENT_OWNER_LIMIT_CHARACTER,
  ERR_MSG_CANNOT_CREATE_COMMENT,
  ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_DATA_TYPE,
  ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_THREAD_ID_LIMIT,
  ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_OWNER_LIMIT,
  ERR_ADD_REPLY_NEED_PROPERTY,
  ERR_MSG_CANNOT_CREATE_REPLY,
  ERR_ADD_REPLY_DATA_TYPE_SPECIFICATION,
  ERR_MSG_CANNOT_CREATE_REPLY_BECAUSE_DATA_TYPE
} = require('../utils/CommonConstanta')

const DomainErrorTranslator = {
  translate (error) {
    return DomainErrorTranslator._directories[error.message] || error
  }
}

DomainErrorTranslator._directories = {
  [ERR_REGISTER_USER_NOT_CONTAIN_NEEDED_PROPERTY]: new InvariantError(ERR_MSG_CANNOT_CREATE_USER),
  [ERR_REGISTER_USER_NOT_MEET_DATA_TYPE_SPECIFICATION]: new InvariantError(ERR_MSG_CANNOT_CREATE_USER_BECAUSE_DATA_TYPE),
  [ERR_REGISTER_USER_USERNAME_LIMIT_CHAR]: new InvariantError(ERR_MSG_CANNOT_CREATE_USER_BECAUSE_USERNAME_LIMIT),
  [ERR_REGISTER_USER_USERNAME_RESTRICTED_CHARACTER]: new InvariantError(ERR_MSG_CANNOT_CREATE_USER_BECAUSE_RESTRICTED_CHARACTER),
  [ERR_LOGIN_NOT_CONTAIN_NEEDED_PROPERTY]: new InvariantError(ERR_MSG_MUST_SEND_USERNAME_AND_PASSWORD),
  [ERR_LOGIN_NOT_MEET_DATA_TYPE_SPECIFICATION]: new InvariantError(ERR_MSG_DATA_TYPE_USERNAME_PASSWORD_MUST_STRING),
  [ERR_REFRESH_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN]: new InvariantError(ERR_MSG_MUST_SEND_REFRESH_TOKEN),
  [ERR_REFRESH_USE_CASE_PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION]: new InvariantError(ERR_MSG_REFRESH_TOKEN_MUST_STRING),
  [ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN]: new InvariantError(ERR_MSG_MUST_SEND_REFRESH_TOKEN),
  [ERR_DELETE_AUTHENTICATION_USE_CASE_NOT_MEET_DATA_TYPE_SPECIFICATION]: new InvariantError(ERR_MSG_REFRESH_TOKEN_MUST_STRING),
  [ERR_ADD_THREAD_NEED_PROPERTY]: new InvariantError(ERR_MSG_CANNOT_CREATE_THREAD),
  [ERR_ADD_THREAD_DATA_TYPE_SPECIFICATION]: new InvariantError(ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_DATA_TYPE),
  [ERR_ADD_THREAD_TITLE_LIMIT_CHARACTER]: new InvariantError(ERR_MSG_CANNOT_CREATE_THREAD_BECAUSE_TITLE_LIMIT),
  [ERR_ADD_COMMENT_NEED_PROPERTY]: new InvariantError(ERR_MSG_CANNOT_CREATE_COMMENT),
  [ERR_ADD_COMMENT_DATA_TYPE_SPECIFICATION]: new InvariantError(ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_DATA_TYPE),
  [ERR_ADD_COMMENT_THREAD_ID_LIMIT_CHARACTER]: new InvariantError(ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_THREAD_ID_LIMIT),
  [ERR_ADD_COMMENT_OWNER_LIMIT_CHARACTER]: new InvariantError(ERR_MSG_CANNOT_CREATE_COMMENT_BECAUSE_OWNER_LIMIT),
  [ERR_ADD_REPLY_NEED_PROPERTY]: new InvariantError(ERR_MSG_CANNOT_CREATE_REPLY),
  [ERR_ADD_REPLY_DATA_TYPE_SPECIFICATION]: new InvariantError(ERR_MSG_CANNOT_CREATE_REPLY_BECAUSE_DATA_TYPE)
}

module.exports = DomainErrorTranslator
